import React from 'react';
import Roster from '../../components/Roster';
import photo from '../../assets/images/mensroster.jpg';

import '../../css/rosters.scss';

const RosterPage = () => (
  <div className="container">
    <div className="page__header">
      2015-2016 Varsity & Novice Men
    </div>
    <div className="image">
      <img alt="" src={photo} />
    </div>
    <div className="roster">
      <Roster
        rosterName={'Varsity Men'}
        names={[
          'Amos Frank',
          'Andy Chung',
          'Arthur Sebes',
          'Ben Bavonese',
          'Brian Osgood',
          'Chris Chen',
          'Daniel Chang',
          'David Yang',
          'Edison Wong',
          'George Man',
          'Ishaan Golding',
          'Jake Tennant',
          'Jason Ke',
          'Jose Fernandez',
          'Michael Giron',
          'Palmer Hayward',
          'Thomas Dwelley',
        ]}
        sides={[
          'no preference',
          'starboard',
          'no preference',
          'port',
          'port',
          'port',
          'starboard',
          'port',
          'coxswain',
          'starboard',
          'coxswain',
          'no preference',
          'starboard',
          'port',
          'starboard',
          'no preference',
          'starboard',
        ]}
        years={[
          'Freshman',
          'Junior',
          'Grad Student',
          'Freshman',
          'Senior',
          'Junior',
          'Sophomore',
          'Junior',
          'Sophomore',
          'Sophomore',
          'Sophomore',
          'Freshman',
          'Freshman',
          'Sophomore',
          'Junior',
          'Senior',
          'Junior',
        ]}
        hometowns={[
          'Vancouver, BC',
          'Burbank, CA',
          'Lyon, France',
          'Ann Arbor, MI',
          'Santa Barbara, CA',
          'Arcadia, CA',
          'Hightstown, NJ',
          'Toronto, ON',
          'Canton, China',
          'San Francisco, CA',
          'Austin, TX',
          'Sacramento, CA',
          'San Diego, CA',
          'Fullerton, CA',
          'Hemet, CA',
          'San Diego, CA',
          'Santa Barbara, CA',
        ]}
        majors={[
          'Undeclared',
          'Economics',
          'Transportation Engineering',
          'Economics',
          'Political Science',
          'Chemical Biology',
          'Molecular & Cell Biology',
          'Chemical & Material Science Eng.',
          'Cognitive Science',
          'Molecular & Cell Biology',
          'Political Science',
          'Molecular & Cell Biology',
          'Undeclared',
          'Ethnic Studies',
          'Development Studies',
          'Mechanical Engineering',
          'Mechanical Engineering',
        ]}
      />
    </div>
    <div className="roster">
      <Roster
        rosterName={'Novice Men'}
        names={[
          'Andrew Capistrano',
          'Andrew Chi',
          'Antonio Sakkis',
          'Chris Webster',
          'Chan Varma',
          'Eric Vengrin',
          'Derek Feng',
          'Jake Yukich',
          'Jameson Mah',
          'Jeffrey Liu',
          'Jonathan Lin',
          'Jonathan Lowery',
          'Joshua Sanders',
          'Kevin Mahoney',
          'Luca Amato',
          'Magne Ledsaak',
          'Mateo Lopez',
          'Michael Eliot',
          'Omid Rhezaii',
          'Peter Birghoffer',
          'Salim Dharamshi',
          'Samson Mataraso',
          'Shaun Singh',
          'Shahzad Shaukat',
          'Taeho Jung',
          'Taylor Wong',
          'Tristan Wasley',
          'Windsor Taro',
        ]}
        sides={[
          'no preference',
          'starboard',
          'port',
          'starboard',
          'coxswain',
          'no preference',
          'port',
          'port',
          'starboard',
          'port',
          'starboard',
          'port',
          'port',
          'no preference',
          'starboard',
          'starboard',
          'port',
          'no preference',
          'starboard',
          'starboard',
          'starboard',
          'port',
          'port',
          'starboard',
          'starboard',
          'starboard',
          'starboard',
          'no preference',
        ]}
        years={[
          'Sophomore',
          'Freshman',
          'Freshman',
          'Sophomore',
          'Freshman',
          'Freshman',
          'Freshman',
          'Freshman',
          'Freshman',
          'Junior',
          'Junior',
          'Junior',
          'Senior',
          'Freshman',
          'Freshman',
          'Junior',
          'Freshman',
          'Freshman',
          'Freshman',
          'Freshman',
          'Freshman',
          'Freshman',
          'Senior',
          'Freshman',
          'Junior',
          'Freshman',
          'Freshman',
          'Senior',
        ]}
        hometowns={[
          'Hong Kong, China',
          'Garden Grove, CA',
          'Houston, TX',
          'Stockton, CA',
          'Bangalore, India',
          'San Diego, CA',
          'Fremont, CA',
          'Los Angeles, CA',
          'Oxnard, CA',
          'Palo Alto, CA',
          'San Jose, CA',
          'San Diego, CA',
          'Clearwater, FL',
          'East Richmond Heights, CA',
          'Los Angeles, CA',
          'Stavanger, Norway',
          'Bakersfield, CA',
          'Huntington Beach, CA',
          'San Diego, CA',
          'Budapest, Hungary',
          'Nairobi, Kenya',
          'Walnut Creek, CA',
          'Berkeley, CA',
          'Lahore, Pakistan',
          'Busan, South Korea',
          'Cary, NC',
          'Laguna Hills, CA',
          'San Antonio, TX',
        ]}
        majors={[
          'Environmental Science',
          'Economics & Pre-Business',
          'Undeclared',
          'Economics',
          'Computer Science',
          'Undeclared',
          'Undeclared',
          'Molecular & Cell Biology',
          'Molecular & Cell Biology',
          'Electrical Engineering & Comp. Sci.',
          'Chemical Biology & Music',
          'Economics',
          'Music',
          'Civil & Environmental Engineering',
          'Political Science',
          'Industrial Economics',
          'Public Health',
          'Pre-Business and Computer Science',
          'Undeclared',
          'Undeclared',
          'History & Economics',
          'Bioengineering',
          'Economics',
          'Undeclared',
          'Japanese',
          'Electrical Engineering & Comp. Sci.',
          'Undeclared',
          'Economics',
        ]}
      />
    </div>
  </div>
);

export default RosterPage;
